log-path: /Users/Mac/LiuChong/Projects/SpringCloud/spring-cloud-atguigu/logs/consumer-dep-feign-log
log-pattern: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{60} - %msg%n'

# 端口设置
server:
  port: 9001

# Eureka客户端设置
eureka:
  client:
    register-with-eureka: false                     # false：不向注册中心注册本服务
    service-url:
      defaultZone: http://eureka-01.com:7001/eureka/,http://eureka-02.com:7002/eureka/,http://eureka-03.com:7003/eureka/

# Feign配置
feign:
  hystrix:
    enabled: true