log-path: /Users/Mac/LiuChong/Projects/SpringCloud/spring-cloud-atguigu/logs/config-server-log
log-pattern: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{60} - %msg%n'

# Config配置
spring:
  application:
    name: microservicecloud-config                                     # 微服务名称
  cloud:
    config:
      server:
        git:
          uri: git@github.com:aolc/microservicecloud-config.git        # GitHub上Git仓库名称
