server:
  port:8001

spring:
  application:
    name: microservicecloud-dept                              #  微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource              #  当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                #  mysql驱动包
    url: jdbc:mysql://47.98.113.199:3306/cloudDB01            #  数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                              #  数据库连接池的最小维持连接数
      initial-size: 5                                          #  初始化连接数
      max-total: 5                                             #  最大连接数
      max-wait-millis: 200                                     #  等待链接获取的最大超时时间


